tx = open ("story/text.txt", "r")
txt=tx.read()
t = []
print(txt[0]=='h')

for i in range(len(txt)):
    if (txt[i]=="\n"): t.append(10); i+=1; t.append(13)
    
    elif ord(txt[i])>31 and ord(txt[i])<96:
        t.append(ord(txt[i]))
    elif ord(txt[i])>96 and ord(txt[i])<123:
        t.append(ord(txt[i])-32)
    elif ord(txt[i])>1040:
        
        if (txt[i]=='ю' or txt[i]=='Ю'): t.append(96)
        elif (txt[i]=='а' or txt[i]=='А'): t.append(97)
        elif (txt[i]=='б' or txt[i]=='Б'): t.append(98)
        elif (txt[i]=='ц' or txt[i]=='Ц'): t.append(99)
        elif (txt[i]=='д' or txt[i]=='Д'): t.append(100)
        elif (txt[i]=='ё' or txt[i]=='Ё' or txt[i]=='е' or txt[i]=='Е'): t.append(101)
        elif (txt[i]=='ф' or txt[i]=='Ф'): t.append(102)
        elif (txt[i]=='г' or txt[i]=='Г'): t.append(103)
        elif (txt[i]=='х' or txt[i]=='Х'): t.append(104)
        elif (txt[i]=='и' or txt[i]=='И'): t.append(105)
        elif (txt[i]=='й' or txt[i]=='Й'): t.append(106)
        elif (txt[i]=='к' or txt[i]=='К'): t.append(107)
        elif (txt[i]=='л' or txt[i]=='Л'): t.append(108)
        elif (txt[i]=='м' or txt[i]=='М'): t.append(109)
        elif (txt[i]=='н' or txt[i]=='Н'): t.append(110)
        elif (txt[i]=='о' or txt[i]=='О'): t.append(111)
        elif (txt[i]=='п' or txt[i]=='П'): t.append(112)
        elif (txt[i]=='я' or txt[i]=='Я'): t.append(113)
        elif (txt[i]=='р' or txt[i]=='Р'): t.append(114)
        elif (txt[i]=='с' or txt[i]=='С'): t.append(115)
        elif (txt[i]=='т' or txt[i]=='Т'): t.append(116)
        elif (txt[i]=='у' or txt[i]=='У'): t.append(117)
        elif (txt[i]=='ж' or txt[i]=='Ж'): t.append(118)
        elif (txt[i]=='в' or txt[i]=='В'): t.append(119)
        elif (txt[i]=='ь' or txt[i]=='Ь' or txt[i]=='ъ' or txt[i]=='Ъ'): t.append(120)
        elif (txt[i]=='ы' or txt[i]=='Ы'): t.append(121)
        elif (txt[i]=='з' or txt[i]=='З'): t.append(122)
        elif (txt[i]=='ш' or txt[i]=='Ш'): t.append(123)
        elif (txt[i]=='э' or txt[i]=='Э'): t.append(124)
        elif (txt[i]=='щ' or txt[i]=='Щ'): t.append(125)
        elif (txt[i]=='ч' or txt[i]=='Ч'): t.append(126)
print(t)
